# For more information: https://laravel.com/docs/sail
version: '3'
services:
  laravel.fpm:
    build:
      context: .
      target: fpm_server
    image: echo-chat/fpm_server
    # We can override any env values here.
    # By default, the .env in the project root will be loaded as the environment for all containers
    environment:
      APP_DEBUG: "true"
    # Mount the codebase, so any code changes we make will be propagated to the running application
    volumes:
      # Here we mount in our codebase so any changes are immediately reflected into the container
      - '.:/opt/apps/echo-chat'
    networks:
      - echo-chat
  laravel.web:
    build:
      context: .
      target: web_server
    image: echo-chat/web_server
    # Expose our application port (80) through a port on our local machine (8080)
    ports:
      - '80:80'
    environment:
      # We need to pass in the new FPM hst as the name of the fpm container on port 9000
      FPM_HOST: "laravel.fpm:9000"
    # Mount the public directory into the container, so we can serve any static files directly when they change
    volumes:
      # Here we mount in our codebase so any changes are immediately reflected into the container
      - './public:/opt/apps/echo-chat/public'
    networks:
      - echo-chat
  # Run the Laravel Scheduler
  laravel.cron:
    build:
      context: .
      target: cron
    image: echo-chat/cron
    # Here we mount in our codebase so any changes are immediately reflected into the container
    volumes:
      # Here we mount in our codebase so any changes are immediately reflected into the container
      - '.:/opt/apps/echo-chat'
    networks:
      - echo-chat
  laravel.websocket:
    build:
      context: .
      target: websocket
    image: echo-chat/websocket
    # Expose our application port (6001) through a port on our local machine (6001)
    ports:
      - '6001:6001'
    volumes:
      # Here we mount in our codebase so any changes are immediately reflected into the container
      - '.:/opt/apps/echo-chat'
  mariadb:
    image: 'mariadb:10'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'echo-chat-mariadb:/var/lib/mysql'
    networks:
      - echo-chat
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'echo-chat-redis:/data'
    networks:
      - echo-chat
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
  laravel.frontend:
    build:
      context: .
      target: frontend
    # Override the default CMD, so we can watch changes to frontend files, and re-transpile them.
    command: [ "npm", "run", "watch" ]
    image: echo-chat/frontend
    volumes:
      # Here we mount in our codebase so any changes are immediately reflected into the container
      - '.:/opt/apps/echo-chat'
      # Add node_modules as singular volume.
      # This prevents our local node_modules from being propagated into the container,
      # So the node_modules can be compiled for each of the different architectures (Local, Image)
      - '/opt/app/node_modules/'
    networks:
      - echo-chat
networks:
  echo-chat:
    driver: bridge
volumes:
  echo-chat-mariadb:
    driver: local
  echo-chat-redis:
    driver: local
